name: build-tmoshell-devkit

on:
  workflow_dispatch:
  push:
    branches: [ workflow-build-tmoshell-reusable ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'
defaults:
  run:
    shell: bash

jobs:
  build:
  uses: tmobile/DevEdge-IoTDevKit-ZephyrSDK/.github/workflows/build.yml@workflow-build-tmoshell-reusable
  with:
    ZEPHYR_APPLICATION: ../DevEdge-IoTDevKit-ZephyrSDK/samples/tmo_shell
    ZEPHYR_BOARD: tmo_dev_edge
