name: workflow-tmo-prv-compatible

on:
  push:
    branches: [ workflow-tmo-prv-compatible ]
  workflow_call:
    inputs:
      ZEPHYR_APPLICATION:
        required: true
        type: string
        default: ../DevEdge-IoTDevKit-ZephyrSDK/samples/tmo_shell
      ZEPHYR_BOARD:
        required: true
        type: string
        default: tmo_dev_edge

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:latest
    steps:
      - name: Clone ${{ github.repository }}
        if: ${{ github.repository != 'tmobile/DevEdge-IoTDevKit-ZephyrSDK' }}
        run: |
          git clone {{ $GITHUB_SERVER_URL }}/${{ github.repository }}
      - name: Clone ZephyrSDK
        working-directory: zephyrproject
        run: |
          git clone https://github.com/tmobile/DevEdge-IoTDevKit-ZephyrSDK.git
      - name: Clone ZephyrRTOS
        working-directory: zephyrproject
        run: |
          git clone https://github.com/tmobile/DevEdge-IoTDevKit-ZephyrRTOS.git
      - name: West Init and Update
        working-directory: zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        run: |
          west init -l .
          west update
      - name: West Build
        working-directory: zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        env: 
          ZEPHYR_BASE: ${{ github.workspace }}/zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
          ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/
        run: |
          west build ${{ inputs.ZEPHYR_APPLICATION }} -p -b ${{ inputs.ZEPHYR_BOARD }}
      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.ZEPHYR_BOARD }}
          path: ${{ github.workspace }}/zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS/build/zephyr/zephyr.*
