name: build-tmo-shell-tmo-dev-edge

# on:
#   workflow_dispatch:
#     branches: [ main ]
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '0 6 * * *'

on:
  push:
    branches: [ workflow-nightly-build ]
  pull_request:
    branches: [ workflow-nightly-build ]
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    steps:
      - uses: actions/checkout@v3
        with:
            path: zephyrproject/DevEdge-IoTDevKit-ZephyrSDK
      - name: West Init
        working-directory: zephyrproject
        run: |
          west init -m https://github.com/tmobile/DevEdge-IoTDevKit-ZephyrRTOS.git --mr tmo-main zephyrproject
      - name: West Update
        working-directory: zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        run: |
          west update
      - name: Build
        working-directory: zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        run: |
          printenv
          west build ../DevEdge-IoTDevKit-ZephyrSDK/samples/tmo_shell -p -b tmo_dev_edge
