name: tmo-nightly-build-tmoshell-devkit

#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '0 6 * * *'

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    steps:
      - uses: actions/checkout@v3
        with:
            path: zephyrproject/DevEdge-IoTDevKit-ZephyrSDK
      - name: West Init
        working-directory: zephyrproject
        run: |
          west init -m https://github.com/tmobile/DevEdge-IoTDevKit-ZephyrRTOS.git --mr tmz-1.17.0-qa DevEdge-IoTDevKit-ZephyrRTOS
      - name: West Update
        working-directory: zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        run: |
          west update
      - name: Build
        working-directory: zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS/zephyr
        env: 
          ZEPHYR_BASE: ${{ github.workspace }}/zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        run: |
          printenv
          west build ../../DevEdge-IoTDevKit-ZephyrSDK/samples/tmo_shell -p -b tmo_dev_edge
