name: tmo-nightly-build-tmoshell-devkit

#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '0 6 * * *'

on:
  workflow_dispatch:
  push:
    branches: [ workflow-nightly-build ]
  pull_request:
    branches: [ workflow-nightly-build ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: zephyrprojectrtos/ci:latest
    steps:
      - uses: actions/checkout@v3
        with:
            path: zephyrproject/DevEdge-IoTDevKit-ZephyrSDK
      - name: West Init
        working-directory: zephyrproject
        run: |
          git clone https://github.com/tmobile/DevEdge-IoTDevKit-ZephyrRTOS.git
      - name: West Init
        working-directory: zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        run: |
          west init -l .
          west update
      - name: Build
        working-directory: zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        env: 
          ZEPHYR_BASE: ${{ github.workspace }}/zephyrproject/DevEdge-IoTDevKit-ZephyrRTOS
        run: |
          printenv
          west build ../DevEdge-IoTDevKit-ZephyrSDK/samples/tmo_shell -p -b tmo_dev_edge
